# Generated by Django 5.2.17 on 2026-09-13 10:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import imest_app.models
from django.conf import settings
from django.db import migrations, models


def backfill_codes(apps, schema_editor):
    Test = apps.get_model('imest_app', 'Test')
    Answer = apps.get_model('imest_app', 'StudentAnswer')
    for test in Test.objects.using(schema_editor.connection.alias).all().iterator():
        code = imest_app.models.generate_test_code()
        while Test.objects.using(schema_editor.connection.alias).filter(code=code).exists():
            code = imest_app.models.generate_test_code()
        test.code = code
        # Existing assessments require review before opening to new students.
        if test.is_finished or Answer.objects.using(schema_editor.connection.alias).filter(test_id=test.pk).exists():
            test.status = 'archived'
        test.duration = min(480, max(1, test.duration))
        test.save(using=schema_editor.connection.alias, update_fields=['code', 'status', 'duration'])


class Migration(migrations.Migration):

    dependencies = [
        ('imest_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deadline', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot', models.JSONField(default=list)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('revision', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='answeroption',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='code',
            field=models.CharField(null=True, editable=False, max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('archived', 'В архиве')], default='draft', max_length=10),
        ),
        migrations.RunPython(backfill_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='test', name='code',
            field=models.CharField(default=imest_app.models.generate_test_code, editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imest_app.answeroption'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imest_app.question'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imest_app.student'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imest_app.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='classroom',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='test',
            name='duration',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(480)]),
        ),
        migrations.AlterField(
            model_name='test',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='test',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imest_app.teacher'),
        ),
        migrations.AddConstraint(
            model_name='test',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gte', 1), ('duration__lte', 480)), name='test_valid_duration'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='imest_app.student'),
        ),
        migrations.AddField(
            model_name='testattempt',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='imest_app.test'),
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.UniqueConstraint(fields=('student', 'test'), name='one_attempt_per_student_test'),
        ),
    ]
