# Generated by Django 5.2.17 on 2026-09-14 02:45

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imest_app', '0002_testattempt_alter_answeroption_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.CreateModel(
            name='AttemptEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField()),
                ('kind', models.CharField(choices=[('hidden', 'hidden'), ('blur', 'blur'), ('fullscreen_exit', 'fullscreen_exit'), ('page_exit', 'page_exit'), ('shortcut', 'shortcut')], max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='imest_app.testattempt')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('attempt', 'event_id'), name='unique_attempt_event')],
            },
        ),
    ]
